language: java
jdk:

  - openjdk8
  - openjdk9
  - openjdk11

script: "mvn --show-version --errors --batch-mode clean verify -DredirectTestOutputToFile=false"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - olamy@apache.org
